
runtime: python
service: frontend
env: flex

entrypoint: streamlit run main.py --server.port $PORT

runtime_config:
    python_version: 3
    
manual_scaling:
  instances: 1
resource:
  cpu: 1
  memory_gb : 0.5
  disk_sixe_gb : 10